HAI
CAN HAS STDIO?
I HAS A VAR
VISIBLE "CAN HAS NUMBAR? "!
GIMMEH VAR
VISIBLE "U SEIZ "!
VISIBLE VAR
IZ VAR BIGR THAN 10?
 YARLY
   BTW this is true
   VISIBLE "BIG NUMBAR!!"
 NOWAI
   BTW this is false
   VISIBLE "LITTL NUMBAR!!"
 KTHX
KTHXBYE
