HAI
CAN HAS STDIO?
I HAS A VAR ITZ 3
GIMMEH YARN
VISIBLE VAR
VISIBLE YARN
LOL VAR R 1
LOL YARN R "HAI"
VISIBLE YARN
IM IN YR LOOP
 UPZ VAR!!
 VISIBLE "I M THIS MENNY YRS OLD: "!
 VISIBLE VAR
 I HAS A KITTENZ
 IM IN YR LOOP
   UPZ KITTENZ!!1
   VISIBLE "I HASD THIS MENNY KITTENZ THIS YR: "!
   VISIBLE KITTENZ
   IZ KITTENZ BIGR THAN 5?
     YARLY
       GTFO
     NOWAI
       VISIBLE "STILL POPPEN EM OUT!!!"
   KTHX
 KTHX
 IZ VAR LIEK 5? GTFO KTHX
KTHX
DIAF 1 "BAI"
KTHXBYE
